### ISSUE TITLE
Change user name assigned in Zero Trust

### ISSUE THREAD

**Issue by itzfnr** [Erisa/discord-oidc-worker#10]
Hi,

I'm not sure if this is outwith your scope, but all my research has drawn ablank. Do you have any idea how to change the "User name" assigned to users with the OIDC worker?

For example, this user has been assigned the username "noreply" based on their e-mail address. How would I go about making their Access username their Discord name?
![image](https://github.com/Erisa/discord-oidc-worker/assets/88922673/4f9e708c-39e0-4e99-a27f-f8c08e3b2fbf)

If you could even just point me in the right direction, that'd be much appreciated.

Thanks,

**Comment by Erisa** [comment]
It's definitely not out of scope because I had the same question when creating this for the first time. I'll keep this issue open to remind me to do more research into this. Currently I am not sure where field that comes from if not the email, but I will check and see if I can find out.

**Comment by itzfnr** [comment]
I've figured out a hacky way round it that is fit for my purpose. 

If I set the email field to a prefix and then their discord ID at a predetermined email address (e.g. "user_490609510734364692@example.com") it's possible for me to use their unique username to do things like SSH short-lived certificates.

I know it's not the *best* solution but works well for my needs and seems to be the only way around this problem.

**Comment by Erisa** [comment]
I never got an answer to this from the team, and as of June I don't work at Cloudflare anymore so I would be even less likely to get someone from the team to answer on that.

Since the documentation doesn't mention this, is vague in general, and the trouble I had getting an answer even when i worked there, I'm going to assume Cloudflare either doesn't have this feature or doesn't care to document it, and I will consider this impossible to implement correctly on my side without changes by Cloudflare.
