### ISSUE TITLE
Use guild member scope for roles

### ISSUE THREAD

**Issue by Lulalaby** [Erisa/discord-oidc-worker#3]
We could use the `guilds.members.read` scope to access [/users/@me/guilds/{guild.id}/member](https://discord.com/developers/docs/resources/user#get-current-user-guild-member) which returns roles.

**Comment by Erisa** [comment]
I didn't know a scope like that existed - is there any documentation for it?

**Comment by Erisa** [comment]
Ah I found it - https://discord.com/developers/docs/resources/user#get-current-user-guild-member

**Comment by Lulalaby** [comment]
Yep yep <3 If you want, I can pr it. Playing anyways rn with it

**Comment by Erisa** [comment]
Feel free - just make sure the README is updated accordingly if bot token requirements are scrapped.

My only concern reading through it is the potential privacy concerns people might have about the fact the application can now access all their information across all the guilds rather than just the ones its a part of:
![image](https://user-images.githubusercontent.com/14004943/209726373-71a58deb-dd60-4a1b-b486-15a048f36a82.png)

To that end perhaps there can be an option in the Worker to either do it this way or do it the current way with a bot token?

If you want to talk more realtime about it feel free to message me (Erisa#9999) on Discord, you can join gg/cloudflaredev if we have no mutual servers.

**Comment by Lulalaby** [comment]
we sure have mutuals :D

**Comment by 0xcaff** [comment]
I tried to get ppl in my discord to adopt this sign in mechanism but the all information across all guilds permission was a dealbreaker for folks. It would be awesome there was some way to relax this permission.

Thanks for building this, its makes it really easy to build stuff around discord servers.

**Comment by kms0219kms** [comment]
Actually , I have implemented this for in case they do not care about the scope : https://github.com/lunaiz-corp/discord-oidc-worker#usage-with-roles-without-bot
